/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;

/**
 *
 * @author mateu
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBacessar = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jLusuario = new javax.swing.JLabel();
        jLsenha = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        jPsenha = new javax.swing.JPasswordField();
        jLfundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jBacessar.setText("Acessar");
        jBacessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBacessarActionPerformed(evt);
            }
        });
        getContentPane().add(jBacessar);
        jBacessar.setBounds(340, 230, 100, 40);

        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });
        getContentPane().add(jBsair);
        jBsair.setBounds(460, 230, 100, 40);

        jLusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLusuario.setText("Usuario");
        getContentPane().add(jLusuario);
        jLusuario.setBounds(340, 120, 60, 20);

        jLsenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLsenha.setText("Senha");
        getContentPane().add(jLsenha);
        jLsenha.setBounds(340, 170, 50, 20);

        jTusuario.setToolTipText("admin");
        getContentPane().add(jTusuario);
        jTusuario.setBounds(420, 110, 140, 30);

        jPsenha.setToolTipText("1234");
        getContentPane().add(jPsenha);
        jPsenha.setBounds(420, 160, 140, 30);

        jLfundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLfundoLogin);
        jLfundoLogin.setBounds(0, 0, 862, 420);

        setSize(new java.awt.Dimension(877, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBacessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBacessarActionPerformed
        if (jTusuario.getText().equalsIgnoreCase("admin") && jPsenha.getText().equals("1234")){
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
        }else{ 
           JOptionPane.showMessageDialog(this, "Senha ou Usuário inválidos");
        }
    }//GEN-LAST:event_jBacessarActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBacessar;
    private javax.swing.JButton jBsair;
    private javax.swing.JLabel jLfundoLogin;
    private javax.swing.JLabel jLsenha;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JPasswordField jPsenha;
    private javax.swing.JTextField jTusuario;
    // End of variables declaration//GEN-END:variables
}
