/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modeloConnection.ConexaoBd;

/**
 *
 * @author mateu
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBd conecta = new ConexaoBd();
    
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFbemVindo = new javax.swing.JInternalFrame();
        jPinternal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBcadMedicos = new javax.swing.JButton();
        jBcadEnfermeiro = new javax.swing.JButton();
        jBcadUsuarios = new javax.swing.JButton();
        jBagenda = new javax.swing.JButton();
        jLpainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBfecharBemVindo = new javax.swing.JButton();
        jLfundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMcadastros = new javax.swing.JMenu();
        jMcadMedicos = new javax.swing.JMenuItem();
        jMcadPacientes = new javax.swing.JMenuItem();
        jMenfermeiro = new javax.swing.JMenuItem();
        jMusuários = new javax.swing.JMenuItem();
        jMrelatorios = new javax.swing.JMenu();
        jMferramentas = new javax.swing.JMenu();
        jMtelaBemVindo = new javax.swing.JMenuItem();
        jMsair1 = new javax.swing.JMenu();
        jMsair2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFbemVindo.setTitle("Bem-Vindo");
        jInternalFbemVindo.setVisible(true);
        jInternalFbemVindo.getContentPane().setLayout(null);

        jPinternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPinternal.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cadastros");
        jPinternal.add(jLabel2);
        jLabel2.setBounds(50, 10, 80, 30);

        jBcadMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeUsuario.png"))); // NOI18N
        jBcadMedicos.setToolTipText("Cadastre os Médicos");
        jBcadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadMedicosActionPerformed(evt);
            }
        });
        jPinternal.add(jBcadMedicos);
        jBcadMedicos.setBounds(50, 60, 80, 89);

        jBcadEnfermeiro.setText("Enfermeiro(a)");
        jBcadEnfermeiro.setToolTipText("Cadastre o(a) Enfermeiro(a)");
        jPinternal.add(jBcadEnfermeiro);
        jBcadEnfermeiro.setBounds(150, 70, 120, 70);

        jBcadUsuarios.setText("Usuários");
        jBcadUsuarios.setToolTipText("Cadastre os Usuários");
        jPinternal.add(jBcadUsuarios);
        jBcadUsuarios.setBounds(290, 70, 110, 70);

        jBagenda.setText("Agenda");
        jBagenda.setToolTipText("Agenda do Médico");
        jPinternal.add(jBagenda);
        jBagenda.setBounds(50, 190, 150, 40);

        jLpainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoBemVindo.jpg"))); // NOI18N
        jPinternal.add(jLpainelFundo);
        jLpainelFundo.setBounds(0, 0, 1060, 250);

        jInternalFbemVindo.getContentPane().add(jPinternal);
        jPinternal.setBounds(-10, 70, 1060, 250);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de gerenciamento de: ");
        jInternalFbemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 370, 30);

        jBfecharBemVindo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBfecharBemVindo.setText("Fechar");
        jBfecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfecharBemVindoActionPerformed(evt);
            }
        });
        jInternalFbemVindo.getContentPane().add(jBfecharBemVindo);
        jBfecharBemVindo.setBounds(880, 0, 160, 70);

        getContentPane().add(jInternalFbemVindo);
        jInternalFbemVindo.setBounds(60, 250, 1060, 360);

        jLfundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaInicial.jpg"))); // NOI18N
        getContentPane().add(jLfundoPrincipal);
        jLfundoPrincipal.setBounds(0, 0, 1180, 640);

        jMcadastros.setText("Cadastros");

        jMcadMedicos.setText("Médicos");
        jMcadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadMedicosActionPerformed(evt);
            }
        });
        jMcadastros.add(jMcadMedicos);

        jMcadPacientes.setText("Pacientes");
        jMcadastros.add(jMcadPacientes);

        jMenfermeiro.setText("Enfermeiro(a)");
        jMcadastros.add(jMenfermeiro);

        jMusuários.setText("Usuários");
        jMcadastros.add(jMusuários);

        jMenuBar1.add(jMcadastros);

        jMrelatorios.setText("Relatorios");
        jMenuBar1.add(jMrelatorios);

        jMferramentas.setText("Ferramentas");

        jMtelaBemVindo.setText("Tela Bem-Vindo");
        jMtelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMtelaBemVindoActionPerformed(evt);
            }
        });
        jMferramentas.add(jMtelaBemVindo);

        jMenuBar1.add(jMferramentas);

        jMsair1.setText("SAIR");

        jMsair2.setText("Sair");
        jMsair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsair2ActionPerformed(evt);
            }
        });
        jMsair1.add(jMsair2);

        jMenuBar1.add(jMsair1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1191, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBfecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfecharBemVindoActionPerformed
        jInternalFbemVindo.dispose();
    }//GEN-LAST:event_jBfecharBemVindoActionPerformed

    private void jMsair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsair2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMsair2ActionPerformed

    private void jMtelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMtelaBemVindoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMtelaBemVindoActionPerformed

    private void jMcadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadMedicosActionPerformed
        FormMedicos tela = new FormMedicos();
        tela.setVisible(true);
    }//GEN-LAST:event_jMcadMedicosActionPerformed

    private void jBcadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadMedicosActionPerformed
        FormMedicos tela = new FormMedicos();
        tela.setVisible(true);
    }//GEN-LAST:event_jBcadMedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagenda;
    private javax.swing.JButton jBcadEnfermeiro;
    private javax.swing.JButton jBcadMedicos;
    private javax.swing.JButton jBcadUsuarios;
    private javax.swing.JButton jBfecharBemVindo;
    private javax.swing.JInternalFrame jInternalFbemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLfundoPrincipal;
    private javax.swing.JLabel jLpainelFundo;
    private javax.swing.JMenuItem jMcadMedicos;
    private javax.swing.JMenuItem jMcadPacientes;
    private javax.swing.JMenu jMcadastros;
    private javax.swing.JMenuItem jMenfermeiro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMferramentas;
    private javax.swing.JMenu jMrelatorios;
    private javax.swing.JMenu jMsair1;
    private javax.swing.JMenuItem jMsair2;
    private javax.swing.JMenuItem jMtelaBemVindo;
    private javax.swing.JMenuItem jMusuários;
    private javax.swing.JPanel jPinternal;
    // End of variables declaration//GEN-END:variables
}
